# fly.toml app configuration file generated for ens-resolver on 2023-07-18T20:18:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ens-resolver"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  [build.args]
    NODE_VERSION = "18"
